version: '3.8'

services:
  # Database Service
  # Named 'db' to match the hostname used in Modele.php ('mysql:host=db;...')
  db:
    image: mysql:8.0
    container_name: monblog-dbb
    restart: always
    environment:
      MYSQL_DATABASE: monblog
      MYSQL_USER: bloguser
      MYSQL_PASSWORD: blogpass
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
      # - ./db.sql:/docker-entrypoint-initdb.d/db.sql   #copie db.sql dans le conteneur MySQL   ; si on utilise  db.sql

  # Web Server Service
  web:
    build: .
    container_name: monblog-webb
    restart: always
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data:
